steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/${_PROJECT_ID}/service-orders", "./CloudRunService_Order"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/service-orders"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "service-orders",
        "--image",
        "gcr.io/${_PROJECT_ID}/service-orders",
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--service-account",
        "${_SERVICE_ACCOUNT}",
      ]