ERROR_ID="ID CAN NOT BE FOUND OR GENERATED"
ERROR_DB="CONNECTION TO DATABASE ERROR"
ERROR_CASH="INSUFFICIENT BALANCE"
ERROR_STOCKS="INSUFFICIENT STOCKS"
ERROR_REQUEST="INCOMPLETE FIELD OR INCORRECT CONTENT-TYPE"
ERROR_DUPLICATE_ORDER="DUPLICATE ORDER"
ERROR_HOURS="CLOSED MARKET"

OPERATION_TYPE=["BUY","SELL"]